apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- scc.yaml
- sa-controller.yaml
- sa-workload.yaml
- workload_role.yaml
- workload_role_binding.yaml
- controller_role.yaml
- controller_role_binding.yaml
namespace: test-freeipa
